In [64]:
from IPython.display import display
import pandas as pd
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression 
from sklearn.metrics import mean_squared_error
from scipy.stats import zscore
import gzip
import os
import csv
from alive_progress import alive_bar
from collections import defaultdict

types = defaultdict(int, token = "string")
numbers = list(range(0,2000)) 
years_Columns = list(range(1500,2019)) 
names = ['token']
names = names + numbers

directory = 'C:/Users/bincl/BA-Thesis/Dataset/2gram'
chunksize_per_df = 20000

In [74]:
df_chunk_list = pd.read_csv('C:/Users/bincl/BA-Thesis/Dataset/3gram/3_20000_nopos_sample.zip', compression= 'zip', header=None, dtype= str, index_col= [0],chunksize= chunksize_per_df, names = years_Columns,sep='\t',engine='python', quoting=csv.QUOTE_NONE)
#df_chunk_list = pd.read_csv('C:/Users/bincl/BA-Thesis/Dataset/3gram/3_20000_nopos_sample.zip', compression= 'zip', header=None, converters = {token: fu}, index_col= [0],chunksize= chunksize_per_df, names = names,sep='\t | ,', quoting=csv.QUOTE_NONE)

In [75]:
for chunk in df_chunk_list:  
    df3gram = pd.DataFrame(index = chunk.index,columns = years_Columns)
    
    for i in chunk.index:
        df3gram[i]
    break 
display(chunk)

,1501,1502,1503,1504,1505,1506,1507,1508,1509,1510,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
1500,,,,,,,,,,,,,,,,,,,,,
""" Bis seine","1736,1,1","1754,1,1","1828,1,1","1840,2,1","1841,1,1","1852,2,2","1867,1,1","1875,2,2","1876,1,1","1884,1,1",...,None,None,None,None,None,None,None,None,None,None
""" -- Vorgehen","1886,2,2","1902,2,2","1907,1,1","1908,1,1","1909,1,1","1916,1,1","1971,1,1","1972,1,1","1973,1,1","1975,2,2",...,None,None,None,None,None,None,None,None,None,None
""" : Oesterreich","1636,1,1","1692,1,1","1743,1,1","1844,1,1","1845,6,6","1850,1,1","1854,1,1","1855,1,1","1856,2,2","1859,3,3",...,None,None,None,None,None,None,None,None,None,None
""" Geht 's","1640,1,1","1698,1,1","1824,2,2","1825,1,1","1830,2,2","1835,4,4","1836,9,7","1837,1,1","1838,1,1","1839,1,1",...,None,None,None,None,None,None,None,None,None,None
""" Geschlecht '","1754,1,1","1854,3,3","1858,1,1","1872,3,3","1875,1,1","1898,2,2","1899,1,1","1900,2,2","1901,2,1","1902,1,1",...,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
""" Wem zu","1717,1,1","1747,2,2","1774,1,1","1793,2,2","1799,3,3","1800,1,1","1808,1,1","1812,1,1","1826,1,1","1837,1,1",...,None,None,None,None,None,None,None,None,None,None
""" I. Kap","1787,1,1","1843,1,1","1853,2,2","1867,1,1","1879,6,5","1903,1,1","1904,1,1","1905,8,8","1908,2,2","1913,1,1",...,None,None,None,None,None,None,None,None,None,None
""" Marcus :","1663,1,1","1761,1,1","1877,1,1","1935,1,1","1936,1,1","1952,1,1","1954,1,1","1962,1,1","1965,1,1","1969,1,1",...,None,None,None,None,None,None,None,None,None,None
""" Unendliche und","1801,1,1","1858,10,10","1859,1,1","1869,1,1","1886,2,2","1887,1,1","1902,2,2","1908,5,5","1912,1,1","1919,1,1",...,None,None,None,None,None,None,None,None,None,None
""" Statt fand","1793,1,1","1800,1,1","1804,1,1","1814,1,1","1815,1,1","1817,1,1","1819,1,1","1824,3,3","1825,3,3","1827,2,2",...,None,None,None,None,None,None,None,None,None,None

In [ ]:

def find_n_gram(direc, find):
    for filename in os.listdir(direc):
        f = os.path.join(direc, filename)
        # checking if it is a file
        if os.path.isfile(f):
            print(f)
            with gzip.open(f,'rt', encoding='utf-8') as input:
                str_arr_csv = input.readlines()
                for line in str_arr_csv:
                    token = line.split("\t")
                    if find == token[0]:
                        return line
                        
    return "line not found" 

def start_the_search(directory,search):
    result = find_n_gram(directory,search)
    
    if result == "line not found":
        print(result)
        exit()
    result = result.split("\t")
    lower_ngram = pd.Series(result[1:],dtype= "string", name = result[0])
    return lower_ngram

In [ ]:
def getLowerLevelString(string):
   first, *middle, last = string.split()
   first = first + " " + ''.join(middle)
   last = ''.join(middle) + " " + last
   return first, last

def MLR(token,ngram):
    print(token)
    first,last = getLowerLevelString(token)
    print(first)
    print(last)
    first = start_the_search(directory,first)
    last = start_the_search(directory,last)
    
    X = pd.concat([first,last],axis=1)
    y = ngram.loc[token]
    reg = LinearRegression()
    reg.fit(X, y) 
    
    return reg.coef_,reg.intercept_,X

def buildApproximation(c1,c2,basevalue,df):
    df = df.astype('float')
    df['scaledFirst'] = df.iloc[:,0].apply(lambda x: x * c1) 
    df['scaledLast'] = df.iloc[:,1].apply(lambda x: x * c2) 
    df['approximation'] = df['scaledFirst'] + df['scaledLast'] + basevalue
    return df

In [ ]:
def compressWithError2gram(firstN,error,df_ngram):
    df_N_gram = df_ngram.head(firstN)
    
    result = []
    all = []
    sum = []
    with alive_bar(df_N_gram.index.values.size) as bar:
        for token in df_N_gram.index.values:
            coef,intercept,dfAprox = MLR(token,df_N_gram)
            c1,c2 = coef
            df = buildApproximation(c1,c2,intercept,dfAprox)
            dfOriginal = pd.DataFrame()
            dfOriginal['values'] = df_ngram.loc[token]
            dfOriginal['values'] = dfOriginal['values'].apply(pd.to_numeric, errors='coerce')
            #dfOriginal= pd.to_numeric(dfOriginal)
            dfOriginal['zscore'] = zscore(dfOriginal)
            df['zscore'] = zscore(df['approximation'])
            
            sum.append(pd.to_numeric(dfOriginal['values']).sum()) 
            
            rmse = mean_squared_error(dfOriginal['zscore'], df['zscore'], squared = False)
            #rmse = mean_squared_error(dfOriginal, df['approximation'])
            if rmse <= error:
                result.append([token,rmse,dfOriginal['values'],dfOriginal['zscore'],df['approximation'],df['zscore']]) 
            all.append(rmse)    
            bar()
    return result, all, sum

In [ ]:
result, all, sum = compressWithError2gram(chunksize_per_df,0.05, df_3gram_chunk)
print(len(result))

In [ ]:
plt.boxplot(all)
plt.show()
rmse_with_error = []

for i in result:
    rmse_with_error.append(i[1])
plt.boxplot(rmse_with_error)
plt.show()

import seaborn as sns

sns.violinplot(x= rmse_with_error, inner="point")

In [ ]:
sns.violinplot(x= all, inner_kws=dict(box_width=15, whis_width=2, color=".8"))

In [ ]:

plt.scatter(sum, all)
plt.xscale('log')
plt.show()