In [2]:
from pyspark.sql import SparkSession
from pyspark.sql.functions import split, col, element_at, slice, size, regexp_extract, transform, when, explode, \
monotonically_increasing_id, map_from_arrays, lit, udf,collect_list, row_number, ceil, map_keys, expr, from_json, min, max
from pyspark.sql.types import ShortType, ArrayType, LongType, StringType
from pyspark.sql import types as T

from IPython.display import display
import pandas as pd
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression 
from sklearn.metrics import mean_squared_error
from scipy.stats import zscore
import gzip
import os
import csv
from alive_progress import alive_bar
from collections import defaultdict
import pandas as pd
from os import listdir
from os.path import isfile, join
import sys



        # checking if it is a file
spark = SparkSession.builder.appName('3gramSQL').getOrCreate()
df1= spark.read.parquet("C:/Users/bincl/BA-Thesis/Dataset/3gram/parquet/orderBy/3gram")
print(df1.head(1))

c:\Users\bincl\AppData\Local\Programs\Python\Python311\Lib\site-packages\scipy\__init__.py:169: UserWarning: A NumPy version >=1.18.5 and <1.26.0 is required for this version of SciPy (detected version 1.26.2
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

[Row(Tokens='Wert ) ,', Data={'1976': 82, '1975': 126, '1853': 2, '1974': 111, '1852': 3, '1973': 98, '1851': 1, '1972': 120, '1850': 8, '1971': 127, '1970': 149, '1859': 4, '1858': 4, '1979': 87, '1857': 3, '1978': 89, '1977': 104, '1909': 44, '1908': 59, '1990': 105, '1987': 81, '1986': 90, '1985': 93, '1984': 76, '1862': 1, '1983': 100, '1861': 1, '1982': 101, '1981': 111, '1980': 100, '1907': 70, '1906': 70, '1905': 65, '1904': 94, '1903': 47, '1869': 2, '1902': 45, '1901': 41, '1989': 85, '1900': 36, '1988': 125, '1919': 41, '1880': 5, '1877': 3, '1910': 74, '1998': 55, '1997': 81, '1875': 1, '1996': 73, '1874': 1, '1995': 117, '1873': 2, '1994': 83, '1872': 1, '1993': 74, '1871': 2, '1992': 91, '1991': 68, '1918': 45, '1917': 45, '1916': 49, '1915': 53, '1914': 55, '1913': 90, '1879': 1, '1912': 100, '1878': 4, '1911': 87, '1999': 101, '1770': 1, '1891': 22, '1890': 12, '1888': 4, '1921': 60, '1887': 24, '1920': 47, '1886': 7, '1885': 14, '1884': 19, '1883': 7, '1881': 2, '1929': 56, '1928': 47, '1927': 46, '1926': 44, '1925': 60, '1924': 15, '1923': 53, '1889': 9, '1922': 60, '1899': 10, '1932': 64, '1898': 18, '1931': 70, '1897': 20, '1930': 78, '1896': 2, '1895': 20, '1894': 23, '1893': 13, '1892': 16, '1819': 1, '1939': 44, '1938': 55, '1937': 50, '1936': 42, '1935': 36, '1934': 40, '1933': 39, '2001': 132, '2000': 108, '1789': 1, '1943': 19, '1788': 1, '1942': 34, '1941': 19, '1786': 1, '1940': 27, '1829': 2, '1949': 28, '1948': 45, '1826': 1, '1947': 20, '1946': 7, '1945': 8, '1823': 5, '1944': 15, '2012': 325, '2011': 334, '2010': 325, '1833': 11, '1954': 72, '2009': 240, '1832': 50, '1953': 38, '2008': 357, '1952': 42, '2007': 288, '1951': 46, '2006': 253, '1950': 20, '2005': 227, '2004': 212, '2003': 156, '2002': 122, '1959': 66, '1958': 65, '1957': 66, '1956': 59, '1955': 66, '1965': 106, '1843': 1, '1964': 95, '2019': 265, '1842': 1, '1963': 81, '2018': 300, '1962': 93, '2017': 309, '1840': 1, '1961': 82, '2016': 269, '1960': 80, '2015': 293, '2014': 325, '2013': 1173, '1849': 1, '1848': 1, '1969': 149, '1968': 136, '1846': 2, '1967': 126, '1845': 1, '1966': 166}, Sum=13381)]

In [3]:
print(df1.tail(1))

[Row(Tokens='mit herbeizufÃ¼hren ,', Data={'1855': 7, '1976': 3, '1854': 1, '1975': 4, '1974': 3, '1973': 1, '1851': 1, '1972': 9, '1971': 6, '1970': 4, '1859': 1, '1979': 8, '1978': 1, '1977': 6, '1909': 6, '1908': 2, '1866': 2, '1987': 2, '1865': 8, '1986': 2, '1864': 1, '1985': 3, '1984': 5, '1983': 3, '1861': 1, '1982': 2, '1981': 1, '1980': 2, '1907': 1, '1905': 5, '1904': 4, '1903': 3, '1869': 2, '1902': 3, '1901': 1, '1989': 2, '1867': 1, '1900': 1, '1988': 2, '1919': 2, '1910': 5, '1998': 2, '1997': 3, '1996': 3, '1995': 9, '1994': 1, '1993': 5, '1871': 2, '1992': 3, '1991': 2, '1916': 9, '1915': 1, '1914': 2, '1913': 5, '1912': 1, '1878': 1, '1911': 6, '1999': 3, '1891': 1, '1890': 3, '1888': 1, '1921': 5, '1887': 1, '1920': 2, '1883': 1, '1881': 3, '1929': 1, '1928': 4, '1927': 2, '1925': 3, '1924': 1, '1922': 3, '1899': 6, '1932': 6, '1930': 1, '1895': 3, '1893': 7, '1892': 4, '1939': 1, '1938': 1, '1937': 1, '1936': 3, '1935': 2, '2001': 7, '2000': 2, '1821': 1, '1942': 1, '1941': 2, '1940': 1, '1948': 3, '1947': 1, '1946': 2, '1944': 1, '2012': 8, '2011': 3, '2010': 2, '1954': 2, '2009': 3, '1953': 2, '2008': 5, '1952': 2, '2007': 2, '1951': 3, '2006': 4, '2004': 3, '2003': 4, '2002': 1, '1958': 2, '1957': 1, '1835': 5, '1956': 6, '1955': 4, '1965': 3, '1843': 6, '1964': 2, '2019': 1, '1963': 1, '2018': 9, '2017': 3, '1961': 3, '2016': 3, '1960': 5, '2015': 2, '2013': 12, '1969': 1, '1847': 1, '1968': 5, '1967': 6, '1845': 1, '1966': 3}, Sum=401)]

In [4]:
df2= spark.read.parquet("C:/Users/bincl/BA-Thesis/Dataset/3gram/parquet/3_20000_nopos_sample/3_20000_nopos_sample.gz/")
print(df2.head(1))

[Row(Tokens='den Sektor der', Data={'1976': 239, '1975': 286, '1974': 243, '1973': 250, '1972': 207, '1971': 247, '1970': 225, '1859': 2, '1979': 210, '1857': 1, '1978': 209, '1977': 228, '1909': 5, '1908': 7, '1990': 122, '1987': 148, '1986': 140, '1985': 232, '1984': 217, '1983': 250, '1982': 245, '1981': 204, '1980': 226, '1907': 2, '1906': 3, '1904': 5, '1901': 2, '1989': 174, '1867': 2, '1900': 2, '1988': 158, '1919': 3, '1880': 2, '1910': 15, '1998': 157, '1997': 125, '1875': 2, '1996': 121, '1995': 123, '1994': 141, '1993': 141, '1992': 143, '1991': 140, '1917': 4, '1916': 11, '1915': 5, '1914': 1, '1912': 1, '1911': 8, '1999': 187, '1921': 4, '1920': 2, '1885': 1, '1883': 5, '1929': 10, '1928': 2, '1927': 6, '1926': 2, '1925': 1, '1924': 2, '1923': 3, '1922': 2, '1932': 10, '1931': 2, '1897': 1, '1930': 6, '1939': 38, '1938': 35, '1937': 11, '1936': 13, '1935': 12, '1934': 6, '1933': 7, '2001': 203, '2000': 185, '1943': 20, '1942': 25, '1941': 29, '1940': 28, '1949': 31, '1948': 26, '1947': 25, '1946': 10, '1824': 2, '1945': 11, '1944': 11, '2012': 213, '2011': 300, '2010': 219, '1954': 76, '2009': 248, '1953': 69, '2008': 324, '1952': 61, '2007': 280, '1951': 53, '2006': 179, '1950': 33, '2005': 199, '2004': 201, '2003': 181, '2002': 206, '1959': 156, '1958': 98, '1957': 107, '1956': 117, '1955': 100, '1965': 249, '1964': 176, '2019': 178, '1963': 164, '2018': 142, '1962': 122, '2017': 152, '1961': 181, '2016': 157, '1960': 162, '2015': 208, '2014': 208, '2013': 675, '1969': 277, '1968': 244, '1967': 241, '1966': 232}, Sum=13796)]

In [5]:
print(df2.tail(1))

[Row(Tokens='1929 erschienenen Roman', Data={'1976': 3, '1975': 2, '1930': 3, '1974': 2, '1973': 3, '1972': 3, '1971': 1, '1970': 8, '1936': 1, '1979': 6, '1978': 2, '1977': 6, '1990': 6, '2001': 8, '2000': 6, '1987': 2, '1986': 5, '1985': 2, '1984': 3, '1983': 12, '1982': 4, '1981': 6, '1980': 3, '1949': 6, '1948': 2, '1946': 2, '1989': 7, '1988': 8, '2012': 1, '2011': 10, '2010': 5, '1954': 2, '1998': 11, '2009': 6, '1997': 4, '2008': 4, '1952': 3, '1996': 8, '2007': 7, '1951': 1, '1995': 6, '2006': 16, '1994': 4, '2005': 12, '1993': 5, '2004': 7, '1992': 3, '2003': 6, '1991': 2, '2002': 14, '1958': 1, '1957': 5, '1999': 7, '1965': 2, '1964': 2, '2019': 1, '2018': 5, '1962': 1, '2017': 5, '2016': 2, '2015': 3, '2014': 13, '2013': 2, '1929': 1, '1968': 5, '1967': 2, '1966': 1}, Sum=317)]

In [6]:
print((df1.count(), len(df1.columns)))
print((df2.count(), len(df2.columns)))

(10800613, 3)
(10800613, 3)

In [7]:
df1.agg(min("Sum"), max("Sum")).show()
df2.agg(min("Sum"), max("Sum")).show()

+--------+---------+
|min(Sum)| max(Sum)|
+--------+---------+
|      40|108947630|
+--------+---------+

+--------+---------+
|min(Sum)| max(Sum)|
+--------+---------+
|      40|108947630|
+--------+---------+

In [8]:
#df1.select("Sum").printSchema

In [9]:
new_df1 =df1.orderBy("Sum", ascending = False)
new_df1.head(1)

[Row(Tokens=', daÃ die', Data={'1583': 286, '1582': 453, '1581': 519, '1580': 302, '1579': 57, '1578': 227, '1699': 1608, '1577': 197, '1698': 2740, '1576': 188, '1697': 2698, '1575': 109, '1696': 1828, '1574': 132, '1695': 1487, '1573': 176, '1694': 2041, '1473': 1, '1594': 225, '1593': 447, '1592': 360, '1591': 194, '1590': 1386, '1589': 215, '1588': 250, '1587': 880, '1586': 312, '1585': 116, '1584': 234, '1599': 609, '1598': 154, '1597': 779, '1475': 4, '1596': 316, '1595': 444, '1492': 61, '1496': 4, '2001': 676503, '2000': 774972, '2012': 510333, '2011': 331790, '2010': 211947, '2009': 233576, '2008': 282774, '2007': 343696, '2006': 392487, '2005': 433919, '2004': 499974, '2003': 540997, '2002': 614877, '2019': 409588, '2018': 436692, '2017': 682046, '2016': 488833, '2015': 581876, '2014': 416862, '2013': 3247443, '1909': 1263831, '1908': 1398539, '1907': 1309975, '1906': 1210244, '1905': 1065377, '1904': 949836, '1903': 676471, '1902': 390986, '1901': 348381, '1900': 330753, '1919': 735032, '1910': 1282138, '1918': 679082, '1917': 729143, '1916': 777532, '1915': 856762, '1914': 1310743, '1913': 1557901, '1912': 1418813, '1911': 1364593, '1809': 14803, '1800': 21985, '1921': 937734, '1920': 871180, '1808': 18858, '1929': 757641, '1807': 15328, '1928': 778908, '1806': 16917, '1927': 728062, '1805': 21452, '1926': 678247, '1804': 24513, '1925': 664213, '1803': 22317, '1924': 484142, '1802': 20934, '1923': 588546, '1801': 21045, '1922': 1006212, '1811': 17024, '1932': 628839, '1810': 21766, '1931': 702452, '1930': 767871, '1819': 35981, '1818': 28587, '1939': 474224, '1817': 31407, '1938': 503624, '1816': 22070, '1937': 536596, '1815': 20402, '1936': 515407, '1814': 14974, '1935': 532882, '1813': 16284, '1934': 540029, '1812': 15895, '1933': 602300, '1701': 3292, '1822': 47387, '1943': 263677, '1700': 3581, '1821': 36315, '1942': 244371, '1820': 39534, '1941': 292551, '1940': 349135, '1709': 1648, '1708': 2729, '1829': 64432, '1707': 2560, '1828': 64515, '1949': 354464, '1706': 1377, '1827': 52903, '1948': 283084, '1705': 1966, '1826': 52746, '1947': 209029, '1704': 1456, '1825': 49392, '1946': 119435, '1703': 1445, '1824': 43437, '1945': 84758, '1702': 2174, '1823': 39315, '1944': 149309, '1712': 4880, '1833': 101280, '1954': 604027, '1711': 1755, '1832': 69623, '1953': 553283, '1710': 3162, '1831': 89983, '1952': 468328, '1830': 74000, '1951': 431981, '1950': 443801, '1719': 4051, '1718': 5271, '1839': 116681, '1717': 3475, '1838': 120331, '1959': 846788, '1716': 2719, '1837': 98890, '1958': 769616, '1715': 4160, '1836': 91055, '1957': 732211, '1714': 3419, '1835': 84693, '1956': 741668, '1713': 2899, '1834': 86591, '1955': 637875, '1602': 627, '1723': 3176, '1844': 170221, '1965': 1084126, '1601': 1060, '1722': 4505, '1843': 154513, '1964': 991327, '1600': 608, '1721': 4678, '1842': 135684, '1963': 948641, '1720': 4890, '1841': 117065, '1962': 985626, '1840': 120373, '1961': 929974, '1960': 888485, '1609': 790, '1608': 342, '1729': 6479, '1607': 615, '1728': 3534, '1849': 113168, '1606': 737, '1727': 3241, '1848': 155678, '1969': 1168184, '1605': 377, '1726': 4889, '1847': 174559, '1968': 1210444, '1604': 189, '1725': 2763, '1846': 196563, '1967': 1202866, '1603': 710, '1724': 3919, '1845': 188925, '1966': 1092514, '1613': 764, '1734': 4451, '1855': 212666, '1976': 954553, '1612': 1444, '1733': 11101, '1854': 210266, '1975': 1033989, '1611': 1065, '1732': 5091, '1853': 202927, '1974': 1002242, '1610': 676, '1731': 5612, '1852': 189474, '1973': 1046884, '1730': 7654, '1851': 194088, '1972': 1101774, '1850': 174659, '1971': 1137420, '1970': 1215525, '1619': 597, '1618': 1349, '1739': 8363, '1617': 604, '1738': 8336, '1859': 212944, '1616': 301, '1737': 6126, '1858': 218128, '1979': 959305, '1615': 689, '1736': 8771, '1857': 210297, '1978': 990957, '1614': 1162, '1735': 7068, '1856': 225365, '1977': 976996, '1990': 904399, '1624': 454, '1745': 13799, '1866': 213247, '1987': 830916, '1623': 133, '1744': 9754, '1865': 244084, '1986': 861071, '1622': 420, '1743': 9522, '1864': 240159, '1985': 895396, '1621': 1085, '1742': 10555, '1863': 228000, '1984': 933784, '1620': 534, '1741': 10024, '1862': 238426, '1983': 968666, '1740': 10996, '1861': 229725, '1982': 953572, '1860': 218990, '1981': 959359, '1980': 1022075, '1509': 1, '1629': 261, '1507': 1, '1628': 493, '1749': 9027, '1627': 1033, '1748': 10730, '1869': 273096, '1626': 851, '1747': 11336, '1868': 250182, '1989': 882094, '1625': 235, '1746': 11638, '1867': 257141, '1988': 888622, '1880': 209540, '1514': 53, '1635': 61, '1756': 10445, '1877': 203558, '1998': 887622, '1634': 196, '1755': 7628, '1876': 187321, '1997': 880756, '1512': 8, '1633': 256, '1754': 12592, '1875': 200040, '1996': 885217, '1632': 302, '1753': 11719, '1874': 235149, '1995': 937687, '1510': 1, '1631': 456, '1752': 10530, '1873': 194009, '1994': 894929, '1630': 454, '1751': 12154, '1872': 176686, '1993': 920456, '1750': 10404, '1871': 169329, '1992': 835041, '1870': 231899, '1991': 849690, '1639': 66, '1638': 288, '1759': 10838, '1637': 157, '1758': 8508, '1879': 219957, '1636': 206, '1757': 11999, '1878': 198098, '1999': 922319, '1770': 15067, '1891': 266742, '1890': 263439, '1525': 4, '1646': 361, '1767': 9783, '1888': 245733, '1524': 54, '1645': 956, '1766': 10484, '1887': 245331, '1523': 1, '1644': 619, '1765': 9974, '1886': 234567, '1643': 157, '1764': 12439, '1885': 238773, '1521': 257, '1642': 97, '1763': 8413, '1884': 216487, '1520': 4, '1641': 321, '1762': 11924, '1883': 206415, '1640': 1639, '1761': 11385, '1882': 233349, '1760': 13151, '1881': 216587, '1529': 3, '1649': 919, '1527': 11, '1648': 264, '1769': 13633, '1647': 118, '1768': 11444, '1889': 243757, '1660': 700, '1781': 22351, '1780': 20005, '1536': 57, '1657': 910, '1778': 16301, '1899': 335547, '1535': 5, '1656': 398, '1777': 18390, '1898': 321092, '1655': 626, '1776': 15657, '1897': 297904, '1533': 14, '1654': 434, '1775': 12900, '1896': 306828, '1532': 17, '1653': 652, '1774': 15157, '1895': 282808, '1531': 25, '1652': 720, '1773': 15996, '1894': 264556, '1530': 26, '1651': 451, '1772': 14437, '1893': 272165, '1650': 487, '1771': 13756, '1892': 258085, '1539': 22, '1538': 8, '1659': 2013, '1537': 7, '1658': 1120, '1779': 15556, '1550': 1, '1671': 1553, '1792': 28098, '1670': 1961, '1791': 24393, '1790': 24874, '1668': 1317, '1789': 22246, '1546': 1, '1667': 380, '1788': 27199, '1545': 253, '1666': 714, '1787': 29043, '1544': 272, '1665': 610, '1786': 27908, '1543': 1, '1664': 1215, '1785': 29772, '1542': 1, '1663': 2932, '1784': 28306, '1541': 87, '1662': 5147, '1783': 24113, '1661': 3759, '1782': 19926, '1549': 9, '1548': 92, '1669': 1858, '1561': 303, '1682': 833, '1560': 51, '1681': 2575, '1680': 1671, '1558': 22, '1679': 1240, '1557': 49, '1678': 1319, '1799': 21958, '1556': 169, '1677': 1570, '1798': 22061, '1555': 17, '1676': 1155, '1797': 24495, '1554': 3, '1675': 1667, '1796': 26217, '1553': 12, '1674': 1145, '1795': 22659, '1552': 3, '1673': 790, '1794': 26587, '1672': 1307, '1793': 26205, '1559': 187, '1572': 398, '1693': 1317, '1571': 224, '1692': 2311, '1570': 327, '1691': 1208, '1690': 2253, '1569': 324, '1568': 31, '1689': 1805, '1567': 50, '1688': 4833, '1566': 45, '1687': 2321, '1565': 125, '1686': 1874, '1564': 46, '1685': 1527, '1563': 85, '1684': 2039, '1562': 89, '1683': 2464}, Sum=108947630)]

In [10]:
new_df2 =df2.sort("Sum", ascending = False)
new_df2.head(1)

[Row(Tokens=', daÃ die', Data={'1583': 286, '1582': 453, '1581': 519, '1580': 302, '1579': 57, '1578': 227, '1699': 1608, '1577': 197, '1698': 2740, '1576': 188, '1697': 2698, '1575': 109, '1696': 1828, '1574': 132, '1695': 1487, '1573': 176, '1694': 2041, '1473': 1, '1594': 225, '1593': 447, '1592': 360, '1591': 194, '1590': 1386, '1589': 215, '1588': 250, '1587': 880, '1586': 312, '1585': 116, '1584': 234, '1599': 609, '1598': 154, '1597': 779, '1475': 4, '1596': 316, '1595': 444, '1492': 61, '1496': 4, '2001': 676503, '2000': 774972, '2012': 510333, '2011': 331790, '2010': 211947, '2009': 233576, '2008': 282774, '2007': 343696, '2006': 392487, '2005': 433919, '2004': 499974, '2003': 540997, '2002': 614877, '2019': 409588, '2018': 436692, '2017': 682046, '2016': 488833, '2015': 581876, '2014': 416862, '2013': 3247443, '1909': 1263831, '1908': 1398539, '1907': 1309975, '1906': 1210244, '1905': 1065377, '1904': 949836, '1903': 676471, '1902': 390986, '1901': 348381, '1900': 330753, '1919': 735032, '1910': 1282138, '1918': 679082, '1917': 729143, '1916': 777532, '1915': 856762, '1914': 1310743, '1913': 1557901, '1912': 1418813, '1911': 1364593, '1809': 14803, '1800': 21985, '1921': 937734, '1920': 871180, '1808': 18858, '1929': 757641, '1807': 15328, '1928': 778908, '1806': 16917, '1927': 728062, '1805': 21452, '1926': 678247, '1804': 24513, '1925': 664213, '1803': 22317, '1924': 484142, '1802': 20934, '1923': 588546, '1801': 21045, '1922': 1006212, '1811': 17024, '1932': 628839, '1810': 21766, '1931': 702452, '1930': 767871, '1819': 35981, '1818': 28587, '1939': 474224, '1817': 31407, '1938': 503624, '1816': 22070, '1937': 536596, '1815': 20402, '1936': 515407, '1814': 14974, '1935': 532882, '1813': 16284, '1934': 540029, '1812': 15895, '1933': 602300, '1701': 3292, '1822': 47387, '1943': 263677, '1700': 3581, '1821': 36315, '1942': 244371, '1820': 39534, '1941': 292551, '1940': 349135, '1709': 1648, '1708': 2729, '1829': 64432, '1707': 2560, '1828': 64515, '1949': 354464, '1706': 1377, '1827': 52903, '1948': 283084, '1705': 1966, '1826': 52746, '1947': 209029, '1704': 1456, '1825': 49392, '1946': 119435, '1703': 1445, '1824': 43437, '1945': 84758, '1702': 2174, '1823': 39315, '1944': 149309, '1712': 4880, '1833': 101280, '1954': 604027, '1711': 1755, '1832': 69623, '1953': 553283, '1710': 3162, '1831': 89983, '1952': 468328, '1830': 74000, '1951': 431981, '1950': 443801, '1719': 4051, '1718': 5271, '1839': 116681, '1717': 3475, '1838': 120331, '1959': 846788, '1716': 2719, '1837': 98890, '1958': 769616, '1715': 4160, '1836': 91055, '1957': 732211, '1714': 3419, '1835': 84693, '1956': 741668, '1713': 2899, '1834': 86591, '1955': 637875, '1602': 627, '1723': 3176, '1844': 170221, '1965': 1084126, '1601': 1060, '1722': 4505, '1843': 154513, '1964': 991327, '1600': 608, '1721': 4678, '1842': 135684, '1963': 948641, '1720': 4890, '1841': 117065, '1962': 985626, '1840': 120373, '1961': 929974, '1960': 888485, '1609': 790, '1608': 342, '1729': 6479, '1607': 615, '1728': 3534, '1849': 113168, '1606': 737, '1727': 3241, '1848': 155678, '1969': 1168184, '1605': 377, '1726': 4889, '1847': 174559, '1968': 1210444, '1604': 189, '1725': 2763, '1846': 196563, '1967': 1202866, '1603': 710, '1724': 3919, '1845': 188925, '1966': 1092514, '1613': 764, '1734': 4451, '1855': 212666, '1976': 954553, '1612': 1444, '1733': 11101, '1854': 210266, '1975': 1033989, '1611': 1065, '1732': 5091, '1853': 202927, '1974': 1002242, '1610': 676, '1731': 5612, '1852': 189474, '1973': 1046884, '1730': 7654, '1851': 194088, '1972': 1101774, '1850': 174659, '1971': 1137420, '1970': 1215525, '1619': 597, '1618': 1349, '1739': 8363, '1617': 604, '1738': 8336, '1859': 212944, '1616': 301, '1737': 6126, '1858': 218128, '1979': 959305, '1615': 689, '1736': 8771, '1857': 210297, '1978': 990957, '1614': 1162, '1735': 7068, '1856': 225365, '1977': 976996, '1990': 904399, '1624': 454, '1745': 13799, '1866': 213247, '1987': 830916, '1623': 133, '1744': 9754, '1865': 244084, '1986': 861071, '1622': 420, '1743': 9522, '1864': 240159, '1985': 895396, '1621': 1085, '1742': 10555, '1863': 228000, '1984': 933784, '1620': 534, '1741': 10024, '1862': 238426, '1983': 968666, '1740': 10996, '1861': 229725, '1982': 953572, '1860': 218990, '1981': 959359, '1980': 1022075, '1509': 1, '1629': 261, '1507': 1, '1628': 493, '1749': 9027, '1627': 1033, '1748': 10730, '1869': 273096, '1626': 851, '1747': 11336, '1868': 250182, '1989': 882094, '1625': 235, '1746': 11638, '1867': 257141, '1988': 888622, '1880': 209540, '1514': 53, '1635': 61, '1756': 10445, '1877': 203558, '1998': 887622, '1634': 196, '1755': 7628, '1876': 187321, '1997': 880756, '1512': 8, '1633': 256, '1754': 12592, '1875': 200040, '1996': 885217, '1632': 302, '1753': 11719, '1874': 235149, '1995': 937687, '1510': 1, '1631': 456, '1752': 10530, '1873': 194009, '1994': 894929, '1630': 454, '1751': 12154, '1872': 176686, '1993': 920456, '1750': 10404, '1871': 169329, '1992': 835041, '1870': 231899, '1991': 849690, '1639': 66, '1638': 288, '1759': 10838, '1637': 157, '1758': 8508, '1879': 219957, '1636': 206, '1757': 11999, '1878': 198098, '1999': 922319, '1770': 15067, '1891': 266742, '1890': 263439, '1525': 4, '1646': 361, '1767': 9783, '1888': 245733, '1524': 54, '1645': 956, '1766': 10484, '1887': 245331, '1523': 1, '1644': 619, '1765': 9974, '1886': 234567, '1643': 157, '1764': 12439, '1885': 238773, '1521': 257, '1642': 97, '1763': 8413, '1884': 216487, '1520': 4, '1641': 321, '1762': 11924, '1883': 206415, '1640': 1639, '1761': 11385, '1882': 233349, '1760': 13151, '1881': 216587, '1529': 3, '1649': 919, '1527': 11, '1648': 264, '1769': 13633, '1647': 118, '1768': 11444, '1889': 243757, '1660': 700, '1781': 22351, '1780': 20005, '1536': 57, '1657': 910, '1778': 16301, '1899': 335547, '1535': 5, '1656': 398, '1777': 18390, '1898': 321092, '1655': 626, '1776': 15657, '1897': 297904, '1533': 14, '1654': 434, '1775': 12900, '1896': 306828, '1532': 17, '1653': 652, '1774': 15157, '1895': 282808, '1531': 25, '1652': 720, '1773': 15996, '1894': 264556, '1530': 26, '1651': 451, '1772': 14437, '1893': 272165, '1650': 487, '1771': 13756, '1892': 258085, '1539': 22, '1538': 8, '1659': 2013, '1537': 7, '1658': 1120, '1779': 15556, '1550': 1, '1671': 1553, '1792': 28098, '1670': 1961, '1791': 24393, '1790': 24874, '1668': 1317, '1789': 22246, '1546': 1, '1667': 380, '1788': 27199, '1545': 253, '1666': 714, '1787': 29043, '1544': 272, '1665': 610, '1786': 27908, '1543': 1, '1664': 1215, '1785': 29772, '1542': 1, '1663': 2932, '1784': 28306, '1541': 87, '1662': 5147, '1783': 24113, '1661': 3759, '1782': 19926, '1549': 9, '1548': 92, '1669': 1858, '1561': 303, '1682': 833, '1560': 51, '1681': 2575, '1680': 1671, '1558': 22, '1679': 1240, '1557': 49, '1678': 1319, '1799': 21958, '1556': 169, '1677': 1570, '1798': 22061, '1555': 17, '1676': 1155, '1797': 24495, '1554': 3, '1675': 1667, '1796': 26217, '1553': 12, '1674': 1145, '1795': 22659, '1552': 3, '1673': 790, '1794': 26587, '1672': 1307, '1793': 26205, '1559': 187, '1572': 398, '1693': 1317, '1571': 224, '1692': 2311, '1570': 327, '1691': 1208, '1690': 2253, '1569': 324, '1568': 31, '1689': 1805, '1567': 50, '1688': 4833, '1566': 45, '1687': 2321, '1565': 125, '1686': 1874, '1564': 46, '1685': 1527, '1563': 85, '1684': 2039, '1562': 89, '1683': 2464}, Sum=108947630)]